### PR TITLE
better raytraced renders

### PR DESCRIPTION
**Pull request by pdp7**

### CODE REVIEW

**Comment by pdp7** [comment]
thanks @Anool

**Comment by pdp7** [comment]
@Anool Something I've wondered about KiCad, it seems like the bottom side is poorly light when ray tracing in kicad.  Is it possible to change the light source?

**Comment by Anool** [comment]
I haven't seen any settings to change default parameters. The "floor" is always "under" the PCB, so when you flip if over, it loses the nice shadows etc.
I'm trying to learn ray tracing in FreeCAD but haven't made much headway yet.

**Comment by pdp7** [comment]
ok, thanks

**Comment by Anool** [comment]
There's some parameters that can be toggled under Ray Tracing Settings in 3D, but nothing more.

**Comment by pdp7** [comment]
Greg Davill tweeted "Preferences -> Render Options -> Raytracing Options -> Add Floors (Un-check)" but I guess that looses the shadows?

**Pull request merged**
