### PR TITLE
added more 3D models for footprints

### PR DESCRIPTION
**Pull request by pdp7**
Thanks to @anool for adding more models.

I opened his fork in KiCad: https://github.com/wyolum/Badge-PCB and created these screenshots:
Screenshot from 2020-01-12 15-36-01
Screenshot from 2020-01-12 15-36-13

Unfortunately, I merged https://github.com/mwelling/Badge-PCB/commit/0c97acd4cb632d7c1c18045bbfa1b6cb3fd3e37d from @mwelling  just now which conflicts so I will need to figure out how to resolve it

### CODE REVIEW

**Comment by Anool** [comment]
Okay. Not sure how to get out of that mess, so let me know how it gets
solved.

I added almost all the models except the Crystal Y1 and the Voltage
Supervisor IC2


Best Regards,

Anool Mahidharia
Work <http://www.lumetron.com/>
DiY <http://www.wyolum.com/>
Hackaday <http://hackaday.com/author/anool/>
HackerSpace <http://www.makersasylum.com>
Git <https://github.com/anool>
Twitter <https://twitter.com/anool>
Flickr <http://www.flickr.com/photos/anool>
Picasa <http://picasaweb.google.com/anool.m>

**Comment by pdp7** [comment]
Attempting to merge https://github.com/wyolum/Badge-PCB/commit/cf54fad4061d5c1899d77fc02288cebf6c239369 into master:
```
pdp7@x1:~/dev/ohs20/ssh/Badge-PCB$ git merge anool/Badge-PCB/master 
Auto-merging badge.kicad_pcb
CONFLICT (content): Merge conflict in badge.kicad_pcb
Removing 3d_part_models/USB_Micro-B_Molex_105017-0001.wrl
Automatic merge failed; fix conflicts and then commit the result.
pdp7@x1:~/dev/ohs20/ssh/Badge-PCB$ git status
On branch master
Your branch is up to date with 'origin/master'.

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:

	renamed:    3d_part_models/545482271_cp.step -> 3d_part_models/0545482271.step
	renamed:    3d_part_models/545482271_cp.wrl -> 3d_part_models/0545482271.wrl
	new file:   3d_part_models/APDS_9962.step
	new file:   3d_part_models/APDS_9962.wrl
	new file:   3d_part_models/BMD_340_A_R077.step
	new file:   3d_part_models/BMD_340_A_R077.wrl
	new file:   3d_part_models/BME680_cp.step
	new file:   3d_part_models/BME680_cp.wrl
	modified:   3d_part_models/JST_GH_SM02B-GHS-TB_1x02-1MP_P1.25mm_Horizontal.step
	modified:   3d_part_models/JST_GH_SM02B-GHS-TB_1x02-1MP_P1.25mm_Horizontal.wrl
	new file:   3d_part_models/LGA-24L_3.5x3_0.43p.step
	new file:   3d_part_models/LGA-24L_3.5x3_0.43p.wrl
	new file:   3d_part_models/SPH0645LM4H_B009.step
	new file:   3d_part_models/SPH0645LM4H_B009.wrl
	new file:   3d_part_models/TL3305AFxxxxG.step
	new file:   3d_part_models/TL3305AFxxxxG.wrl
	renamed:    3d_part_models/USB_Micro-B_Molex_105017-0001.step -> 3d_part_models/USB-MicroB_Molex_105017.step
	new file:   3d_part_models/USB-MicroB_Molex_105017.wrl
	deleted:    3d_part_models/USB_Micro-B_Molex_105017-0001.wrl
	modified:   Badge-PCB.pretty/0545482271.kicad_mod
	modified:   Badge-PCB.pretty/APDS-9960.kicad_mod
	modified:   Badge-PCB.pretty/PQFN24P43_350X300X102L35X23N.kicad_mod
	modified:   Badge-PCB.pretty/PSON80P300X300X100-8N.kicad_mod
	modified:   Badge-PCB.pretty/RIGADO_BMD-340-A-R.kicad_mod
	modified:   Badge-PCB.pretty/SON50P300X200X100-9N-D.kicad_mod
	modified:   Badge-PCB.pretty/SPH0645LM4H-B.kicad_mod
	modified:   Badge-PCB.pretty/SW_SPST_TL3305A.kicad_mod
	modified:   Badge-PCB.pretty/USB_Micro-B_Molex-105017-0001.kicad_mod
	new file:   CAD/badge-PCB.step
	new file:   CAD/badge-PCB_01.png
	new file:   CAD/badge-PCB_02.png
	new file:   renders/badge-03.png
	new file:   renders/badge-04.png
	new file:   renders/badge-05.png
	new file:   renders/badge-06.png
	new file:   renders/badge-07.png

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   badge.kicad_pcb

pdp7@x1:~/dev/ohs20/ssh/Badge-PCB$ 

```
```
pdp7@x1:~/dev/ohs20/ssh/Badge-PCB$ git diff
diff --cc badge.kicad_pcb
index fd02bed,5f4a72f..0000000
--- a/badge.kicad_pcb
+++ b/badge.kicad_pcb
@@@ -2818,8 -2838,8 +2838,13 @@@
      )
    )
  
++<<<<<<< HEAD
 +  (module Badge-PCB:0545482271 (layer B.Cu) (tedit 5E1994EE) (tstamp 5E14A325)
 +    (at 121.6937 97.48944 90)
++=======
+   (module Badge-PCB:0545482271 (layer B.Cu) (tedit 5E1B0914) (tstamp 5E14A325)
+     (at 120.4478 97.5 90)
++>>>>>>> anool/Badge-PCB/master
      (descr 0545482271)
      (tags Connector)
      (path /5E28E58C)
```
I choose the version from master (where @mwelling had been doing routing) and deleted the lines from @Anool (becuase I figure the changes for the 3D models have less of a functional impact):
```
  (module Badge-PCB:0545482271 (layer B.Cu) (tedit 5E1994EE) (tstamp 5E14A325)
    (at 121.6937 97.48944 90)
    (descr 0545482271)
    (tags Connector)
    (path /5E28E58C)
    (attr smd)
    (fp_text reference TFT1 (at 0 0 -90) (layer B.SilkS)
      (effects (font (size 0.762 0.762) (thickness 0.1524)) (justify mirror))
    )
```
```
pdp7@x1:~/dev/ohs20/ssh/Badge-PCB$ git commit
[master 772e2de] Merge remote-tracking branch 'anool/Badge-PCB/master'
```
```
pdp7@x1:~/dev/ohs20/ssh/Badge-PCB$ git push
Enumerating objects: 75, done.
Counting objects: 100% (61/61), done.
Delta compression using up to 8 threads
Compressing objects: 100% (43/43), done.
Writing objects: 100% (43/43), 4.23 MiB | 2.42 MiB/s, done.
Total 43 (delta 20), reused 0 (delta 0)
remote: Resolving deltas: 100% (20/20), completed with 15 local objects.
To github.com:oshwabadge2020/Badge-PCB.git
   5350fd1..772e2de  master -> master
```

**Comment by pdp7** [comment]
@mwelling please update your repo: https://github.com/oshwabadge2020/Badge-PCB/commit/772e2de79209ce93261a174abec6bde0133d34a1

@Anool if you open https://github.com/oshwabadge2020/Badge-PCB/commit/772e2de79209ce93261a174abec6bde0133d34a1, does it look like you expect in the render?

thanks!

**Comment by Anool** [comment]
Yes, 772e2de, does look as expected.

I created the last two missing 3d models (Y1 and IC2) in FreeCAD and added
them to the board.

You can pull again.


Best Regards,

Anool Mahidharia
Work <http://www.lumetron.com/>
DiY <http://www.wyolum.com/>
Hackaday <http://hackaday.com/author/anool/>
HackerSpace <http://www.makersasylum.com>
Git <https://github.com/anool>
Twitter <https://twitter.com/anool>
Flickr <http://www.flickr.com/photos/anool>
Picasa <http://picasaweb.google.com/anool.m>

**Comment by pdp7** [comment]
@Anool thanks, I have updated master in this repo

**Pull request merged**
