### PR TITLE
merge update with 3D models from Anool

### PR DESCRIPTION
**Pull request by pdp7**

### CODE REVIEW

**Comment by pdp7** [comment]
@mwelling @acamilo  - fyi

@Anool - thanks!

**Comment by pdp7** [comment]
@Anool any advice on how to edit .STP files?

I have this STEP file:
http://stp-3d-models.e-switch.com/stp3dmodels/TL3305CFxxxxG.stp
from:
https://www.digikey.de/short/zc1b3v

Screenshot from 2020-01-12 12-57-45
is taller than the datasheet:
Screenshot from 2020-01-10 23-44-13
Screenshot from 2020-01-10 23-37-16

**Comment by Anool** [comment]
Looks good to me. The drawing says total height is 7mm and actuator height
is 4mm.
That's what is shows up as in the STEP file too.


Best Regards,

Anool Mahidharia
Work <http://www.lumetron.com/>
DiY <http://www.wyolum.com/>
Hackaday <http://hackaday.com/author/anool/>
HackerSpace <http://www.makersasylum.com>
Git <https://github.com/anool>
Twitter <https://twitter.com/anool>
Flickr <http://www.flickr.com/photos/anool>
Picasa <http://picasaweb.google.com/anool.m>

**Comment by pdp7** [comment]
@Anool Ah!  I see I was not reading the datasheet correctly.  I see the drawing shows the model is correct for that part: TL3305CF260QG Drawing
http://spec_sheets.e-switch.com/specs/P010473.pdf
Screenshot from 2020-01-12 14-15-51


@mwelling @acamilo I think we do want a shorter switch.  Maybe:
https://www.digikey.de/product-detail/en/e-switch/TL3305AF260QG/EG5353CT-ND/5816198

**Comment by Anool** [comment]
I added most of the other 3D footprints.

[image: badge-03.png]
[image: badge-04.png]

Best Regards,

Anool Mahidharia
Work <http://www.lumetron.com/>
DiY <http://www.wyolum.com/>
Hackaday <http://hackaday.com/author/anool/>
HackerSpace <http://www.makersasylum.com>
Git <https://github.com/anool>
Twitter <https://twitter.com/anool>
Flickr <http://www.flickr.com/photos/anool>
Picasa <http://picasaweb.google.com/anool.m>

**Comment by Anool** [comment]
Shorter buttons

[image: badge-05.png]
[image: badge-06.png]
[image: badge-07.png]
Best Regards,

Anool Mahidharia
Work <http://www.lumetron.com/>
DiY <http://www.wyolum.com/>
Hackaday <http://hackaday.com/author/anool/>
HackerSpace <http://www.makersasylum.com>
Git <https://github.com/anool>
Twitter <https://twitter.com/anool>
Flickr <http://www.flickr.com/photos/anool>
Picasa <http://picasaweb.google.com/anool.m>

**Comment by pdp7** [comment]
@Anool thank you.  I forgot to merge a change from @mwelling fork until now, so I can't merge your new changes.  Could you possibly merge in the change from michael? https://github.com/mwelling/Badge-PCB/commit/0c97acd4cb632d7c1c18045bbfa1b6cb3fd3e37d

Using @Anool fork, I opened in KiCad and the render looks great:
Screenshot from 2020-01-12 15-36-13
Screenshot from 2020-01-12 15-36-01

**Pull request merged**
